version: 2



sources:
    - name: jaffle_shop
      database: raw
      freshness:
       warn_after: {count: 12, period: hour}
       error_after: {count: 24, period: hour}
      loaded_at_field: _elt_loaded_at

      tables:
        - name: orders
          freshness: # make this a little more strict
           warn_after: {count: 12, period: hour}
           error_after: {count: 24, period: hour}
          loaded_at_field: _elt_loaded_at
        - name: customers
          freshness: null
    - name: stripe
      database: raw
      tables:
        - name: payment